# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from njord.v1 import config_service_pb2 as njord_dot_v1_dot_config__service__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in njord/v1/config_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConfigServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetConfig = channel.unary_unary(
                '/njord.v1.ConfigService/GetConfig',
                request_serializer=njord_dot_v1_dot_config__service__pb2.GetConfigRequest.SerializeToString,
                response_deserializer=njord_dot_v1_dot_config__service__pb2.NjordConfig.FromString,
                _registered_method=True)
        self.StreamConfig = channel.unary_stream(
                '/njord.v1.ConfigService/StreamConfig',
                request_serializer=njord_dot_v1_dot_config__service__pb2.StreamConfigRequest.SerializeToString,
                response_deserializer=njord_dot_v1_dot_config__service__pb2.NjordConfig.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/njord.v1.ConfigService/GetStatus',
                request_serializer=njord_dot_v1_dot_config__service__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=njord_dot_v1_dot_config__service__pb2.ServerStatus.FromString,
                _registered_method=True)
        self.AddLocation = channel.unary_unary(
                '/njord.v1.ConfigService/AddLocation',
                request_serializer=njord_dot_v1_dot_config__service__pb2.AddLocationRequest.SerializeToString,
                response_deserializer=njord_dot_v1_dot_config__service__pb2.ConfigResponse.FromString,
                _registered_method=True)
        self.RemoveLocation = channel.unary_unary(
                '/njord.v1.ConfigService/RemoveLocation',
                request_serializer=njord_dot_v1_dot_config__service__pb2.RemoveLocationRequest.SerializeToString,
                response_deserializer=njord_dot_v1_dot_config__service__pb2.ConfigResponse.FromString,
                _registered_method=True)
        self.UpdateLocation = channel.unary_unary(
                '/njord.v1.ConfigService/UpdateLocation',
                request_serializer=njord_dot_v1_dot_config__service__pb2.UpdateLocationRequest.SerializeToString,
                response_deserializer=njord_dot_v1_dot_config__service__pb2.ConfigResponse.FromString,
                _registered_method=True)
        self.UpdateForecastSettings = channel.unary_unary(
                '/njord.v1.ConfigService/UpdateForecastSettings',
                request_serializer=njord_dot_v1_dot_config__service__pb2.UpdateForecastSettingsRequest.SerializeToString,
                response_deserializer=njord_dot_v1_dot_config__service__pb2.ConfigResponse.FromString,
                _registered_method=True)
        self.UpdateEnrichmentConfig = channel.unary_unary(
                '/njord.v1.ConfigService/UpdateEnrichmentConfig',
                request_serializer=njord_dot_v1_dot_config__service__pb2.UpdateEnrichmentConfigRequest.SerializeToString,
                response_deserializer=njord_dot_v1_dot_config__service__pb2.ConfigResponse.FromString,
                _registered_method=True)
        self.UpdateBudget = channel.unary_unary(
                '/njord.v1.ConfigService/UpdateBudget',
                request_serializer=njord_dot_v1_dot_config__service__pb2.UpdateBudgetRequest.SerializeToString,
                response_deserializer=njord_dot_v1_dot_config__service__pb2.ConfigResponse.FromString,
                _registered_method=True)
        self.TriggerPoll = channel.unary_unary(
                '/njord.v1.ConfigService/TriggerPoll',
                request_serializer=njord_dot_v1_dot_config__service__pb2.TriggerPollRequest.SerializeToString,
                response_deserializer=njord_dot_v1_dot_config__service__pb2.TriggerPollResponse.FromString,
                _registered_method=True)


class ConfigServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetConfig(self, request, context):
        """Read
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddLocation(self, request, context):
        """Location Management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveLocation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateLocation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateForecastSettings(self, request, context):
        """Forecast Settings
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateEnrichmentConfig(self, request, context):
        """Enrichment
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBudget(self, request, context):
        """Budget
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerPoll(self, request, context):
        """Operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConfigServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfig,
                    request_deserializer=njord_dot_v1_dot_config__service__pb2.GetConfigRequest.FromString,
                    response_serializer=njord_dot_v1_dot_config__service__pb2.NjordConfig.SerializeToString,
            ),
            'StreamConfig': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamConfig,
                    request_deserializer=njord_dot_v1_dot_config__service__pb2.StreamConfigRequest.FromString,
                    response_serializer=njord_dot_v1_dot_config__service__pb2.NjordConfig.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=njord_dot_v1_dot_config__service__pb2.GetStatusRequest.FromString,
                    response_serializer=njord_dot_v1_dot_config__service__pb2.ServerStatus.SerializeToString,
            ),
            'AddLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.AddLocation,
                    request_deserializer=njord_dot_v1_dot_config__service__pb2.AddLocationRequest.FromString,
                    response_serializer=njord_dot_v1_dot_config__service__pb2.ConfigResponse.SerializeToString,
            ),
            'RemoveLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveLocation,
                    request_deserializer=njord_dot_v1_dot_config__service__pb2.RemoveLocationRequest.FromString,
                    response_serializer=njord_dot_v1_dot_config__service__pb2.ConfigResponse.SerializeToString,
            ),
            'UpdateLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateLocation,
                    request_deserializer=njord_dot_v1_dot_config__service__pb2.UpdateLocationRequest.FromString,
                    response_serializer=njord_dot_v1_dot_config__service__pb2.ConfigResponse.SerializeToString,
            ),
            'UpdateForecastSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateForecastSettings,
                    request_deserializer=njord_dot_v1_dot_config__service__pb2.UpdateForecastSettingsRequest.FromString,
                    response_serializer=njord_dot_v1_dot_config__service__pb2.ConfigResponse.SerializeToString,
            ),
            'UpdateEnrichmentConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateEnrichmentConfig,
                    request_deserializer=njord_dot_v1_dot_config__service__pb2.UpdateEnrichmentConfigRequest.FromString,
                    response_serializer=njord_dot_v1_dot_config__service__pb2.ConfigResponse.SerializeToString,
            ),
            'UpdateBudget': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBudget,
                    request_deserializer=njord_dot_v1_dot_config__service__pb2.UpdateBudgetRequest.FromString,
                    response_serializer=njord_dot_v1_dot_config__service__pb2.ConfigResponse.SerializeToString,
            ),
            'TriggerPoll': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerPoll,
                    request_deserializer=njord_dot_v1_dot_config__service__pb2.TriggerPollRequest.FromString,
                    response_serializer=njord_dot_v1_dot_config__service__pb2.TriggerPollResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'njord.v1.ConfigService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('njord.v1.ConfigService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConfigService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/njord.v1.ConfigService/GetConfig',
            njord_dot_v1_dot_config__service__pb2.GetConfigRequest.SerializeToString,
            njord_dot_v1_dot_config__service__pb2.NjordConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/njord.v1.ConfigService/StreamConfig',
            njord_dot_v1_dot_config__service__pb2.StreamConfigRequest.SerializeToString,
            njord_dot_v1_dot_config__service__pb2.NjordConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/njord.v1.ConfigService/GetStatus',
            njord_dot_v1_dot_config__service__pb2.GetStatusRequest.SerializeToString,
            njord_dot_v1_dot_config__service__pb2.ServerStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/njord.v1.ConfigService/AddLocation',
            njord_dot_v1_dot_config__service__pb2.AddLocationRequest.SerializeToString,
            njord_dot_v1_dot_config__service__pb2.ConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/njord.v1.ConfigService/RemoveLocation',
            njord_dot_v1_dot_config__service__pb2.RemoveLocationRequest.SerializeToString,
            njord_dot_v1_dot_config__service__pb2.ConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/njord.v1.ConfigService/UpdateLocation',
            njord_dot_v1_dot_config__service__pb2.UpdateLocationRequest.SerializeToString,
            njord_dot_v1_dot_config__service__pb2.ConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateForecastSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/njord.v1.ConfigService/UpdateForecastSettings',
            njord_dot_v1_dot_config__service__pb2.UpdateForecastSettingsRequest.SerializeToString,
            njord_dot_v1_dot_config__service__pb2.ConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateEnrichmentConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/njord.v1.ConfigService/UpdateEnrichmentConfig',
            njord_dot_v1_dot_config__service__pb2.UpdateEnrichmentConfigRequest.SerializeToString,
            njord_dot_v1_dot_config__service__pb2.ConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateBudget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/njord.v1.ConfigService/UpdateBudget',
            njord_dot_v1_dot_config__service__pb2.UpdateBudgetRequest.SerializeToString,
            njord_dot_v1_dot_config__service__pb2.ConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerPoll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/njord.v1.ConfigService/TriggerPoll',
            njord_dot_v1_dot_config__service__pb2.TriggerPollRequest.SerializeToString,
            njord_dot_v1_dot_config__service__pb2.TriggerPollResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
